/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rexsdesktop.view;

import java.awt.CardLayout;
import java.awt.Container;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/**
 *
 * @author user
 */
public class LoginSingUp extends javax.swing.JFrame {

    rubikFont f = new rubikFont();
    public LoginSingUp() {
        initComponents();
        cambiarCardLayoutPanel("InicioSesion");
        LoginBG.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("resources/loginbg.png")).getImage().getScaledInstance(500, 625, Image.SCALE_SMOOTH)));
//        jLabel1.setFont(f.light.deriveFont(30f));
        btnCardRecuperarClave.setContentAreaFilled(false);
        btnCardRegistro.setContentAreaFilled(false);
        btnSignGoogle.setContentAreaFilled(false);
        btnSignFacebook.setContentAreaFilled(false);
        btnCardInicioSesion.setContentAreaFilled(false);
        btnCardInicioSesion1.setContentAreaFilled(false);
        btnSignGoogle1.setContentAreaFilled(false);
        btnSignFacebook1.setContentAreaFilled(false);

    }
    public final void cambiarCardLayoutPanel(String nombre)
    {
        CardLayout cl = (CardLayout)(CardLayoutPanel.getLayout());
        
        if(nombre.equals("InicioSesion"))
        {
            cl.show(CardLayoutPanel, "InicioSesion");
        }
        else if(nombre.equals("Registro"))
        {
            cl.show(CardLayoutPanel, "Registro");
        }
        else if(nombre.equals("RecuperarClave"))
        {
            cl.show(CardLayoutPanel, "RecuperarClave");
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LoginBG = new javax.swing.JLabel();
        CardLayoutPanel = new javax.swing.JPanel();
        PanelIniciarSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnCardRecuperarClave = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        btnCardRegistro = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnSignGoogle = new javax.swing.JButton();
        btnSignFacebook = new javax.swing.JButton();
        PanelRegistro = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        btnIniciarSesion1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        btnCardInicioSesion = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnSignGoogle1 = new javax.swing.JButton();
        btnSignFacebook1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        panelRecuperarClave = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel("<html>Ingresa el correo electrónico con el que te registraste.</html>");
        jLabel19 = new javax.swing.JLabel();
        btnIniciarSesion2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnCardInicioSesion1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel("<html>Enviaremos un código de verificación para comprobar que eres tú.</html>");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setAutoscrolls(true);
        jPanel2.setEnabled(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 625));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginBG.setAlignmentY(0.0F);
        LoginBG.setIconTextGap(0);
        LoginBG.setPreferredSize(new java.awt.Dimension(500, 625));
        jPanel2.add(LoginBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, 625));

        CardLayoutPanel.setPreferredSize(new java.awt.Dimension(500, 625));
        CardLayoutPanel.setLayout(new java.awt.CardLayout());

        PanelIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        PanelIniciarSesion.setPreferredSize(new java.awt.Dimension(500, 625));

        jLabel1.setFont(new java.awt.Font("Rubik Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(46, 56, 77));
        jLabel1.setText("Inicia sesión");
        jLabel1.setPreferredSize(new java.awt.Dimension(131, 28));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/rexslogo.png"))); // NOI18N

        jTextField1.setBackground(new java.awt.Color(249, 250, 255));
        jTextField1.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(46, 56, 77));
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));

        jLabel2.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(135, 152, 173));
        jLabel2.setText("Ingresa tus datos para continuar.");

        jLabel4.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(176, 186, 201));
        jLabel4.setText("CORREO ELECTRÓNICO");

        jLabel5.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(176, 186, 201));
        jLabel5.setText("CONTRASEÑA");

        jPasswordField1.setBackground(new java.awt.Color(249, 250, 255));
        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(46, 56, 77));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));
        jPasswordField1.setEchoChar('\u2022');

        btnCardRecuperarClave.setBackground(new java.awt.Color(255, 255, 255));
        btnCardRecuperarClave.setFont(new java.awt.Font("Rubik", 0, 10)); // NOI18N
        btnCardRecuperarClave.setForeground(new java.awt.Color(176, 186, 201));
        btnCardRecuperarClave.setText("¿OLVIDASTE TU CONTRASEÑA? ");
        btnCardRecuperarClave.setBorder(null);
        btnCardRecuperarClave.setBorderPainted(false);
        btnCardRecuperarClave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCardRecuperarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardRecuperarClaveActionPerformed(evt);
            }
        });

        btnIniciarSesion.setBackground(new java.awt.Color(46, 91, 255));
        btnIniciarSesion.setFont(new java.awt.Font("Rubik Medium", 0, 12)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Rubik Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(112, 112, 112));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("o");

        jSeparator2.setForeground(new java.awt.Color(193, 193, 193));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 193, 193)));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(100, 2));

        jLabel7.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(176, 186, 201));
        jLabel7.setText("¿No tienes una cuenta?");

        btnCardRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnCardRegistro.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        btnCardRegistro.setForeground(new java.awt.Color(46, 91, 255));
        btnCardRegistro.setText("Registrate");
        btnCardRegistro.setBorder(null);
        btnCardRegistro.setBorderPainted(false);
        btnCardRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCardRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardRegistroActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(193, 193, 193));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 193, 193)));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(100, 2));

        btnSignGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/btn_google_signin_light_normal_web.png"))); // NOI18N
        btnSignGoogle.setBorderPainted(false);
        btnSignGoogle.setIconTextGap(0);
        btnSignGoogle.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/btn_google_signin_light_pressed_web.png"))); // NOI18N

        btnSignFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/continuefacebook.png"))); // NOI18N
        btnSignFacebook.setBorderPainted(false);
        btnSignFacebook.setIconTextGap(0);

        javax.swing.GroupLayout PanelIniciarSesionLayout = new javax.swing.GroupLayout(PanelIniciarSesion);
        PanelIniciarSesion.setLayout(PanelIniciarSesionLayout);
        PanelIniciarSesionLayout.setHorizontalGroup(
            PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIniciarSesionLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelIniciarSesionLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelIniciarSesionLayout.createSequentialGroup()
                        .addGroup(PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelIniciarSesionLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCardRegistro)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(PanelIniciarSesionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCardRecuperarClave)))
                .addGap(137, 137, 137))
            .addGroup(PanelIniciarSesionLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelIniciarSesionLayout.setVerticalGroup(
            PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIniciarSesionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCardRecuperarClave)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnCardRegistro))
                .addGroup(PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIniciarSesionLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIniciarSesionLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIniciarSesionLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSignGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        CardLayoutPanel.add(PanelIniciarSesion, "InicioSesion");

        PanelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        PanelRegistro.setPreferredSize(new java.awt.Dimension(500, 625));

        jLabel8.setFont(new java.awt.Font("Rubik Light", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(46, 56, 77));
        jLabel8.setText("Regístrate ahora");
        jLabel8.setPreferredSize(new java.awt.Dimension(131, 28));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/rexslogo.png"))); // NOI18N

        jTextField2.setBackground(new java.awt.Color(249, 250, 255));
        jTextField2.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(46, 56, 77));
        jTextField2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));

        jLabel10.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(135, 152, 173));
        jLabel10.setText("Explora la Expotécnica Ricaldone.");

        jLabel11.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(176, 186, 201));
        jLabel11.setText("CORREO ELECTRÓNICO");

        jLabel12.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(176, 186, 201));
        jLabel12.setText("CONTRASEÑA");

        jPasswordField2.setBackground(new java.awt.Color(249, 250, 255));
        jPasswordField2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(46, 56, 77));
        jPasswordField2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));
        jPasswordField2.setEchoChar('\u2022');

        btnIniciarSesion1.setBackground(new java.awt.Color(46, 91, 255));
        btnIniciarSesion1.setFont(new java.awt.Font("Rubik Medium", 0, 12)); // NOI18N
        btnIniciarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion1.setText("Crear cuenta");
        btnIniciarSesion1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnIniciarSesion1.setBorderPainted(false);

        jLabel13.setFont(new java.awt.Font("Rubik Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(112, 112, 112));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("o");

        jSeparator4.setForeground(new java.awt.Color(193, 193, 193));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 193, 193)));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSeparator4.setPreferredSize(new java.awt.Dimension(100, 2));

        jLabel14.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(176, 186, 201));
        jLabel14.setText("¿Ya tienes una cuenta?");

        btnCardInicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCardInicioSesion.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        btnCardInicioSesion.setForeground(new java.awt.Color(46, 91, 255));
        btnCardInicioSesion.setText("Inicia sesión");
        btnCardInicioSesion.setBorder(null);
        btnCardInicioSesion.setBorderPainted(false);
        btnCardInicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCardInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardInicioSesionActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(193, 193, 193));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 193, 193)));
        jSeparator5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSeparator5.setPreferredSize(new java.awt.Dimension(100, 2));

        btnSignGoogle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/btn_google_signin_light_normal_web.png"))); // NOI18N
        btnSignGoogle1.setBorderPainted(false);
        btnSignGoogle1.setIconTextGap(0);
        btnSignGoogle1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/btn_google_signin_light_pressed_web.png"))); // NOI18N

        btnSignFacebook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/continuefacebook.png"))); // NOI18N
        btnSignFacebook1.setBorderPainted(false);
        btnSignFacebook1.setIconTextGap(0);

        jTextField3.setBackground(new java.awt.Color(249, 250, 255));
        jTextField3.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(46, 56, 77));
        jTextField3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));

        jLabel15.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(176, 186, 201));
        jLabel15.setText("NOMBRE COMPLETO");

        javax.swing.GroupLayout PanelRegistroLayout = new javax.swing.GroupLayout(PanelRegistro);
        PanelRegistro.setLayout(PanelRegistroLayout);
        PanelRegistroLayout.setHorizontalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignFacebook1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignGoogle1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3)
                            .addGroup(PanelRegistroLayout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(btnIniciarSesion1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRegistroLayout.createSequentialGroup()
                                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRegistroLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCardInicioSesion)))
                                .addGap(0, 13, Short.MAX_VALUE)))
                        .addGap(137, 137, 137))))
        );
        PanelRegistroLayout.setVerticalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(1, 1, 1)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(1, 1, 1)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btnCardInicioSesion))
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSignGoogle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignFacebook1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        CardLayoutPanel.add(PanelRegistro, "Registro");

        panelRecuperarClave.setBackground(new java.awt.Color(255, 255, 255));
        panelRecuperarClave.setPreferredSize(new java.awt.Dimension(500, 625));

        jLabel16.setFont(new java.awt.Font("Rubik Light", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(46, 56, 77));
        jLabel16.setText("Recupera tu contraseña");
        jLabel16.setPreferredSize(new java.awt.Dimension(131, 28));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/rexslogo.png"))); // NOI18N

        jTextField4.setBackground(new java.awt.Color(249, 250, 255));
        jTextField4.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(46, 56, 77));
        jTextField4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));

        jLabel18.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(135, 152, 173));

        jLabel19.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(176, 186, 201));
        jLabel19.setText("CORREO ELECTRÓNICO");

        btnIniciarSesion2.setBackground(new java.awt.Color(46, 91, 255));
        btnIniciarSesion2.setFont(new java.awt.Font("Rubik Medium", 0, 12)); // NOI18N
        btnIniciarSesion2.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion2.setText("Enviar código");
        btnIniciarSesion2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnIniciarSesion2.setBorderPainted(false);

        jLabel22.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(176, 186, 201));
        jLabel22.setText("Regresa para");

        btnCardInicioSesion1.setBackground(new java.awt.Color(255, 255, 255));
        btnCardInicioSesion1.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        btnCardInicioSesion1.setForeground(new java.awt.Color(46, 91, 255));
        btnCardInicioSesion1.setText("Iniciar sesión");
        btnCardInicioSesion1.setBorder(null);
        btnCardInicioSesion1.setBorderPainted(false);
        btnCardInicioSesion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCardInicioSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardInicioSesion1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(135, 152, 173));

        javax.swing.GroupLayout panelRecuperarClaveLayout = new javax.swing.GroupLayout(panelRecuperarClave);
        panelRecuperarClave.setLayout(panelRecuperarClaveLayout);
        panelRecuperarClaveLayout.setHorizontalGroup(
            panelRecuperarClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRecuperarClaveLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(panelRecuperarClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIniciarSesion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRecuperarClaveLayout.createSequentialGroup()
                        .addGroup(panelRecuperarClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRecuperarClaveLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel22)
                                .addGap(5, 5, 5)
                                .addComponent(btnCardInicioSesion1)))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addGap(137, 137, 137))
        );
        panelRecuperarClaveLayout.setVerticalGroup(
            panelRecuperarClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecuperarClaveLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addGap(100, 100, 100)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(1, 1, 1)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnIniciarSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRecuperarClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(btnCardInicioSesion1))
                .addGap(291, 291, 291))
        );

        CardLayoutPanel.add(panelRecuperarClave, "RecuperarClave");

        getContentPane().add(CardLayoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCardRecuperarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardRecuperarClaveActionPerformed
        cambiarCardLayoutPanel("RecuperarClave");
    }//GEN-LAST:event_btnCardRecuperarClaveActionPerformed

    private void btnCardRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardRegistroActionPerformed
        cambiarCardLayoutPanel("Registro");
    }//GEN-LAST:event_btnCardRegistroActionPerformed

    private void btnCardInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardInicioSesionActionPerformed
        cambiarCardLayoutPanel("InicioSesion");
    }//GEN-LAST:event_btnCardInicioSesionActionPerformed

    private void btnCardInicioSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardInicioSesion1ActionPerformed
        cambiarCardLayoutPanel("InicioSesion");
    }//GEN-LAST:event_btnCardInicioSesion1ActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        Admin fAdmin = new Admin();
        this.setVisible(false);
        fAdmin.setLocationRelativeTo(null);
        fAdmin.setDefaultCloseOperation(EXIT_ON_CLOSE);
        fAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSingUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardLayoutPanel;
    private javax.swing.JLabel LoginBG;
    private javax.swing.JPanel PanelIniciarSesion;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JButton btnCardInicioSesion;
    private javax.swing.JButton btnCardInicioSesion1;
    private javax.swing.JButton btnCardRecuperarClave;
    private javax.swing.JButton btnCardRegistro;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnIniciarSesion1;
    private javax.swing.JButton btnIniciarSesion2;
    private javax.swing.JButton btnSignFacebook;
    private javax.swing.JButton btnSignFacebook1;
    private javax.swing.JButton btnSignGoogle;
    private javax.swing.JButton btnSignGoogle1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panelRecuperarClave;
    // End of variables declaration//GEN-END:variables
}
