/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rexsdesktop.modal;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rexsdesktop.controller.Sections;
import rexsdesktop.view.Admin;
import static rexsdesktop.view.Admin.jPanel12;
/**
 * Clase que contiene el Panel para modificar una especialidad.
 * @author artur
 */
public class ModalModificarEspecialidad extends javax.swing.JPanel {

    /**
     * Creates new form ModalModificarEspecialidad
     */
    DefaultTableModel modelo = new DefaultTableModel();
    public ModalModificarEspecialidad() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelarModal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel67 = new javax.swing.JLabel();
        txtEspecialidadModal = new javax.swing.JTextField();
        btnModificarModal = new javax.swing.JButton();
        idTipo = new javax.swing.JLabel();
        jLIdEspecialidad = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();

        btnCancelarModal.setBackground(new java.awt.Color(247, 214, 218));
        btnCancelarModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnCancelarModal.setForeground(new java.awt.Color(214, 54, 73));
        btnCancelarModal.setText("Cancelar");
        btnCancelarModal.setBorderPainted(false);

        jSeparator1.setForeground(new java.awt.Color(164, 164, 164));

        jLabel67.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(176, 186, 201));
        jLabel67.setText("Especialidad");

        txtEspecialidadModal.setBackground(new java.awt.Color(249, 250, 255));
        txtEspecialidadModal.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        txtEspecialidadModal.setForeground(new java.awt.Color(46, 56, 77));
        txtEspecialidadModal.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));
        txtEspecialidadModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadModalActionPerformed(evt);
            }
        });
        txtEspecialidadModal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEspecialidadModalKeyTyped(evt);
            }
        });

        btnModificarModal.setBackground(new java.awt.Color(213, 222, 255));
        btnModificarModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnModificarModal.setForeground(new java.awt.Color(46, 91, 255));
        btnModificarModal.setText("Modficar");
        btnModificarModal.setBorderPainted(false);
        btnModificarModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarModalActionPerformed(evt);
            }
        });

        idTipo.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        idTipo.setForeground(new java.awt.Color(176, 186, 201));

        jLIdEspecialidad.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLIdEspecialidad.setForeground(new java.awt.Color(176, 186, 201));

        jLabel70.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(176, 186, 201));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(idTipo)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLIdEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnModificarModal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarModal))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEspecialidadModal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(242, 242, 242)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLIdEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEspecialidadModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(idTipo))
        );
    }// </editor-fold>//GEN-END:initComponents
    
   
    
    
    private void btnModificarModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarModalActionPerformed
        Sections Conexion = new Sections();
        //JOptionPane.showMessageDialog(null, String.valueOf(jComboBox1.getSelectedIndex() + 1));

        try {
            if (txtEspecialidadModal.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Existen campos vacios");
            }else{
            Conexion.setIdEspecialidad(Integer.parseInt(jLabel70.getText()));
            Conexion.setEspecialidad(txtEspecialidadModal.getText());
            if (Conexion.ActualizarEspecialidad()) {
                JOptionPane.showMessageDialog(null, "Datos modificados correctamente");
                Admin.jPanel12.removeAll();
                Sections CargarEspecialidad = new Sections();
                CargarEspecialidad.CrearPanelesEspecialidades(jPanel12);
            } else {
                JOptionPane.showMessageDialog(null, "Error al modficar datos");
                
            }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR GLOBAL");
        }
    }//GEN-LAST:event_btnModificarModalActionPerformed

    private void txtEspecialidadModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadModalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadModalActionPerformed

    private void txtEspecialidadModalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspecialidadModalKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit().beep();
            
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingresar solo Letras");
        }
    }//GEN-LAST:event_txtEspecialidadModalKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarModal;
    private javax.swing.JButton btnModificarModal;
    public javax.swing.JLabel idTipo;
    private javax.swing.JLabel jLIdEspecialidad;
    private javax.swing.JLabel jLabel67;
    public static javax.swing.JLabel jLabel70;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField txtEspecialidadModal;
    // End of variables declaration//GEN-END:variables
}
