/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rexsdesktop.modal;

import java.awt.CardLayout;
import javax.swing.JDialog;

/**
 *
 * @author Carlos Herrera
 */
public class ModalInformacionEspecialidades extends javax.swing.JPanel {

    private JDialog parent;
    private int especialidad;

    /**
     * Creates new form ModalInformacionEspecialidades
     */
    public ModalInformacionEspecialidades(JDialog parent, int Especialidad) {
        this.parent = parent;
        this.especialidad = Especialidad;
        initComponents();
        String espe = "ERROR";
        switch (especialidad) {
            case 1:
                espe = "Tercer Ciclo";
                break;
            case 2:
                espe = "Diseño";
                break;
            case 3:
                espe = "Arquitectura";
                break;
            case 4:
                espe = "Software";
                break;
            case 5:
                espe = "Eca";
                break;
            case 6:
                espe = "Emca";
                break;
            case 7:
                espe = "Itec";
                break;
            case 8:
                espe = "Auto";
                break;
            case 9:
                espe = "Conta";
                break;
            default:
                espe = "Software";
                break;
        }
        cambiarCardLayoutPanel(espe);
    }

    private void cambiarCardLayoutPanel(String nombre) {
        CardLayout cl = (CardLayout) (panelCardLayout.getLayout());
        cl.show(panelCardLayout, nombre);
    }

    private void cerrarDialog() {
        parent.setVisible(false);
        parent.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnCancelarModal = new javax.swing.JButton();
        panelCardLayout = new javax.swing.JPanel();
        TercerCiclo = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel70 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        Auto = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        Conta = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        Itec = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        Arquitectura = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        Emca = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Eca = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Diseño = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Software = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(164, 164, 164));

        btnCancelarModal.setBackground(new java.awt.Color(247, 214, 218));
        btnCancelarModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnCancelarModal.setForeground(new java.awt.Color(214, 54, 73));
        btnCancelarModal.setText("Cerrar");
        btnCancelarModal.setBorderPainted(false);
        btnCancelarModal.setDefaultCapable(false);
        btnCancelarModal.setFocusPainted(false);
        btnCancelarModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModalActionPerformed(evt);
            }
        });

        panelCardLayout.setLayout(new java.awt.CardLayout());

        TercerCiclo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/Tercer Ciclo.png"))); // NOI18N

        jSeparator10.setForeground(new java.awt.Color(164, 164, 164));

        jLabel70.setFont(new java.awt.Font("Rubik Light", 0, 36)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Tercer Ciclo");

        jLabel73.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("<html>\n<h2>Descripción:</h2>\n<p align=\"justify\">\nAgregado al pensum académico normado por el MINED, la institución imparte asignaturas de carácter formativo tales como Formación Cristiana, Informática e introducción a la Tecnología, así mismo se implementan los siguientes programas.\n</p>\n</html>");

        jLabel77.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel77.setText("<html>\n<h2>Programa ROBÓTICA EDUCATIVA:</h2>\n<p align=\"justify\">\nEs el programa que busca fomentar el gusto por la tecnología, la investigación y la ciencia. Mediante una tecnología única e innovadora, los alumnos construyen modelos mecatrónicos con materiales especializados y reciclados, adquieren conocimientos en las áreas de: electrónica, eléctrica, máquinas simples, programación y ciencias.\n</p>\n</html>");

        jLabel78.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("<html>\n<h2>Programa INTELLECTUS:</h2>\n<p align=\"justify\">\nEs un programa de intervención educativa, destinado al fortalecimiento de las habilidades del pensamiento, que busca fundamentalmente enseñar “a pensar” a partir de un acompañamiento que realiza el profesor a través de la mediación.\n</p>\n</html>");

        jLabel79.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("<html>\n<p align=\"justify\">\nAdemás ofrecemos: Educacion musical, Dibujo Técnico, Programación con Arduino\n</p>\n</html>");

        javax.swing.GroupLayout TercerCicloLayout = new javax.swing.GroupLayout(TercerCiclo);
        TercerCiclo.setLayout(TercerCicloLayout);
        TercerCicloLayout.setHorizontalGroup(
            TercerCicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator10)
            .addGroup(TercerCicloLayout.createSequentialGroup()
                .addGroup(TercerCicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TercerCicloLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(TercerCicloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(TercerCicloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TercerCicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TercerCicloLayout.createSequentialGroup()
                                .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel69)
                                .addGap(0, 75, Short.MAX_VALUE))
                            .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(TercerCicloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel79)))
                .addContainerGap())
        );
        TercerCicloLayout.setVerticalGroup(
            TercerCicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TercerCicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel70)
                .addGap(10, 10, 10)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TercerCicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCardLayout.add(TercerCiclo, "Tercer Ciclo");

        Auto.setBackground(new java.awt.Color(255, 255, 255));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/Auto.png"))); // NOI18N

        jSeparator9.setForeground(new java.awt.Color(164, 164, 164));

        jLabel62.setFont(new java.awt.Font("Rubik Light", 0, 36)); // NOI18N
        jLabel62.setText("Mantenimiento Automotriz");

        jLabel63.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("<html>\n<h2>Áreas de desempeño laboral:</h2>\n</html>");

        jLabel64.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("<html> <ul> <li>Mecánico de planta para servicio rápido.</li> <li>Supervisor de mantenimiento.</li> <li>Mecánico para mantenimiento de equipo pesado.</li> <li>Asesor de ventas de repuestos automotrices.</li> <li>Dueño de taller automotriz.</li> <li>Jefe de personal de mantenimiento automotriz.</li> </ul> </html>");

        jLabel65.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("<html>\n<h2>Descripción:</h2>\n<p align=\"justify\">\nEl Bachiller Técnico en Desarrollo de Software, es un técnico de nivel medio, preparado para incorporarse a los procesos de desarrollo de aplicaciones de escritorio, intranet, web, dispositivos móviles, así como la creación y gestión de diversos tipos de bases de datos, y la instalación, configuración y mantenimiento de servidores, todo esto para aplicar adecuaciones o desarrollo de componentes de software en diversas áreas económicas y sociales en las cuales la cuantificación numérica de información, datos y la innovación es requerida.\n</p>\n</html>");

        jLabel66.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("<html>\n<h2>Título:</h2>\n<p align=\"justify\">\nBachiller técnico en Mantenimiento Automotriz.\n</p>\n</html>");

        jLabel67.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("<html> <h2>Labororatorios Especializados:</h2> </html>");

        jLabel68.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("<html> <ul>\n <li>Taller de automotriz. Área dedicada a la formación en la especialidad de Automotriz esta cuenta con los requerimientos de infraestructura y equipo para el mantenimiento de Automotores.</li>\n</ul> </html>");

        javax.swing.GroupLayout AutoLayout = new javax.swing.GroupLayout(Auto);
        Auto.setLayout(AutoLayout);
        AutoLayout.setHorizontalGroup(
            AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator9)
            .addGroup(AutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutoLayout.createSequentialGroup()
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AutoLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AutoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AutoLayout.createSequentialGroup()
                        .addGroup(AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AutoLayout.createSequentialGroup()
                                .addComponent(jLabel67)
                                .addGap(30, 30, 30)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel62)
                .addGap(191, 191, 191))
        );
        AutoLayout.setVerticalGroup(
            AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutoLayout.createSequentialGroup()
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AutoLayout.createSequentialGroup()
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AutoLayout.createSequentialGroup()
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        panelCardLayout.add(Auto, "Auto");

        Conta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/Contaduria.png"))); // NOI18N

        jSeparator8.setForeground(new java.awt.Color(164, 164, 164));

        jLabel11.setFont(new java.awt.Font("Rubik Light", 0, 36)); // NOI18N
        jLabel11.setText("Administrativo Contable");

        jLabel55.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("<html>\n<h2>Áreas de desempeño laboral:</h2>\n</html>");

        jLabel56.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("<html>\n <ul> \n<li>Asesor de negocios.</li> \n<li>Asistente de recursos humanos.</li> \n<li>Asistente contable.</li>\n <li>Gerente de su propia empresa.</li>\n <li>Asistente administrativo.</li>\n </ul> </html>");

        jLabel57.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("<html>\n<h2>Descripción:</h2>\n<p align=\"justify\">\nEl bachillerato Técnico Vocacional Administrativo Contable, brinda las competencias para lograr potenciar las diferentes habilidades pre-profesionales aplicadas para diseñar, organizar y controlar información financiera y económica, relacionada con las operaciones empresariales, procesos de control interno, contabilidad, mercadotecnia y administración de los distintos sectores que conforman la economía; efectuando técnicas e interpretación correcta de normas, procedimientos, políticas y leyes.\n</p>\n</html>");

        jLabel58.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("<html>\n<h2>Título:</h2>\n<p align=\"justify\">\nBachiller técnico administrativo contable\n</p>\n</html>");

        jLabel59.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("<html> <h2>Labororatorios Especializados:</h2> </html>");

        jLabel60.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("<html> <ul>\n <li>Laboratorio de contabilidad. Laboratorio especializado para el trabajo de la especialidad del área contable que cuenta con software afines</li>\n</ul> </html>");

        javax.swing.GroupLayout ContaLayout = new javax.swing.GroupLayout(Conta);
        Conta.setLayout(ContaLayout);
        ContaLayout.setHorizontalGroup(
            ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator8)
            .addGroup(ContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContaLayout.createSequentialGroup()
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContaLayout.createSequentialGroup()
                        .addGroup(ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContaLayout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addGap(30, 30, 30)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(191, 191, 191))
        );
        ContaLayout.setVerticalGroup(
            ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ContaLayout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        panelCardLayout.add(Conta, "Conta");

        Itec.setBackground(new java.awt.Color(255, 255, 255));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/Itec.png"))); // NOI18N

        jSeparator7.setForeground(new java.awt.Color(164, 164, 164));

        jLabel10.setFont(new java.awt.Font("Rubik Light", 0, 28)); // NOI18N
        jLabel10.setText("Infraestructura tecnológica y servicios informáticos.");

        jLabel48.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("<html>\n<h2>Áreas de desempeño laboral:</h2>\n</html>");

        jLabel49.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("<html> <ul> <li>Operador de centros de datos.</li> <li>Encargado de infraestructura tecnológica.</li> <li>Administrador de servicios de red o sistemas de información operativos.</li> <li>Auxiliar de auditoría de sistemas.</li>  </ul> </html>");

        jLabel50.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("<html>\n<h2>Descripción:</h2>\n<p align=\"justify\">\nLa especialidad en Infraestructura Tecnológica y Servicios Informáticos (ITSI) proporciona al estudiante las herramientas necesarias para desarrollar habilidades y destrezas en mantenimiento preventivo y correctivo de computadoras, configuración y mantenimiento de los equipos informáticos en estado óptimo para su buen desempeño, instalación y administración de redes locales; también es capaz de proveer soporte técnico a las empresas e implementar políticas de procedimientos técnicos.\n</p>\n</html>");

        jLabel51.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("<html>\n<h2>Título:</h2>\n<p align=\"justify\">\nBachiller técnico en Infraestructura tecnológica y servicios informáticos.\n</p>\n</html>");

        jLabel52.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("<html> <h2>Labororatorios Especializados:</h2> </html>");

        jLabel53.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("<html> <ul>\n <li>Lab de Mantenimiento de computadoras. Área utilizada para prácticas de mantenimiento tanto en software como en hardware.</li>\n <li>Cisco Networking Academy. Laboratorio para la formación en redes de computadoras con tecnología CISCO</li>\n</ul> </html>");

        javax.swing.GroupLayout ItecLayout = new javax.swing.GroupLayout(Itec);
        Itec.setLayout(ItecLayout);
        ItecLayout.setHorizontalGroup(
            ItecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator7)
            .addGroup(ItecLayout.createSequentialGroup()
                .addGroup(ItecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItecLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ItecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItecLayout.createSequentialGroup()
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ItecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ItecLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ItecLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ItecLayout.createSequentialGroup()
                                .addGroup(ItecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ItecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ItecLayout.createSequentialGroup()
                                        .addComponent(jLabel52)
                                        .addGap(30, 30, 30))))))
                    .addGroup(ItecLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ItecLayout.setVerticalGroup(
            ItecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItecLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(ItecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItecLayout.createSequentialGroup()
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ItecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItecLayout.createSequentialGroup()
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(ItecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        panelCardLayout.add(Itec, "Itec");

        Arquitectura.setBackground(new java.awt.Color(255, 255, 255));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/Arquitectura.png"))); // NOI18N

        jSeparator6.setForeground(new java.awt.Color(164, 164, 164));

        jLabel9.setFont(new java.awt.Font("Rubik Light", 0, 36)); // NOI18N
        jLabel9.setText("Arquitectura");

        jLabel41.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("<html>\n<h2>Áreas de desempeño laboral:</h2>\n</html>");

        jLabel42.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("<html> <ul>  <li>Dibujante arquitectónico.</li> <li>Operador de software en CAD.</li><li>Asistente en proyectos arquitectónicos</li> </ul> </html>");

        jLabel43.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("<html>\n<h2>Descripción:</h2>\n<p align=\"justify\">\nLa especialidad de arquitectura está orientada a la formación de técnicos en el área de diseño arquitectónico de edificaciones, busca el desarrollo de competencias para elaborar planos arquitectónicos, planos hidráulicos y eléctricos, planos de cimentaciones y estructura, aborda el proceso constructivo, sistemas constructivos de mayor uso en El Salvador, prepara en el dominio de la topografía para realizar mediciones de terrenos con estación total y GPS, sin dejar de lado la tecnología informática por medio del uso de sistemas CAD, Revit Architecture, Auto CAD, Civil CAD y Photoshop para la digitalización y renderización de proyectos arquitectónicos.\n</p>\n</html>");

        jLabel44.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("<html>\n<h2>Título:</h2>\n<p align=\"justify\">\nBachiller técnico en Arquitectura.\n</p>\n</html>");

        jLabel45.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("<html> <h2>Labororatorios Especializados:</h2> </html>");

        jLabel46.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("<html> <ul>\n <li>Lab en práctica de AutoCAD. Laboratorio especializado para el trabajo de la especialidad de Arquitectura que cuenta con software de diseño asistido por computadora como lo es Autocad, Arquitectural Revit entre otros.</li>\n</ul> </html>");

        javax.swing.GroupLayout ArquitecturaLayout = new javax.swing.GroupLayout(Arquitectura);
        Arquitectura.setLayout(ArquitecturaLayout);
        ArquitecturaLayout.setHorizontalGroup(
            ArquitecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6)
            .addGroup(ArquitecturaLayout.createSequentialGroup()
                .addGroup(ArquitecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArquitecturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ArquitecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ArquitecturaLayout.createSequentialGroup()
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(ArquitecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ArquitecturaLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ArquitecturaLayout.createSequentialGroup()
                                .addGroup(ArquitecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ArquitecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ArquitecturaLayout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addGap(30, 30, 30))))))
                    .addGroup(ArquitecturaLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ArquitecturaLayout.setVerticalGroup(
            ArquitecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArquitecturaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(ArquitecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArquitecturaLayout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ArquitecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ArquitecturaLayout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42))
                    .addGroup(ArquitecturaLayout.createSequentialGroup()
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelCardLayout.add(Arquitectura, "Arquitectura");

        Emca.setBackground(new java.awt.Color(255, 255, 255));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/Emca.png"))); // NOI18N

        jSeparator5.setForeground(new java.awt.Color(164, 164, 164));

        jLabel8.setFont(new java.awt.Font("Rubik Light", 0, 36)); // NOI18N
        jLabel8.setText("Electromécanica");

        jLabel34.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("<html>\n<h2>Áreas de desempeño laboral:</h2>\n</html>");

        jLabel35.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("<html> <ul> <li>Mantenimiento mécanico.</li> <li>Mantenimiento electrónico de maquinaria y equipo.</li> <li>Diagramador y operados de CNC.</li> <li>Mantenimiento eléctrico industrial.</li> <li>Automatización de procesos industriales.</li> </ul> </html>");

        jLabel36.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("<html>\n<h2>Descripción:</h2>\n<p align=\"justify\">\nEl Bachiller Técnico vocacional en Electromecánica es capaz de operar, montar y mantener maquinaria y equipo industrial en las diferentes áreas tales como: Torno, Fresa, CNC’s, Equipos de Soldadura convencional, autógena y especiales, Elementos neumáticos e hidráulicos, Motores eléctricos y Autómatas programables para la realización de líneas automatizadas de producción de acuerdo con los reglamentos y normativas vigentes, siguiendo los protocolos de calidad, seguridad e higiene ocupacional y de prevención de riesgos laborales.\n</p>\n</html>");

        jLabel37.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("<html>\n<h2>Título:</h2>\n<p align=\"justify\">\nBachiller técnico en Electromécanica.\n</p>\n</html>");

        jLabel38.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("<html> <h2>Labororatorios Especializados:</h2> </html>");

        jLabel39.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("<html> <ul>\n <li>Taller de mecánica (torno, fresadora, ajuste y soldadura).</li>\n <li>Taller de electricidad y maquinas eléctricas. </li>\n <li>Lab. de neumática. </li>\n <li>Lab. de Mecatrónica. </li>\n</ul> </html>");

        javax.swing.GroupLayout EmcaLayout = new javax.swing.GroupLayout(Emca);
        Emca.setLayout(EmcaLayout);
        EmcaLayout.setHorizontalGroup(
            EmcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(EmcaLayout.createSequentialGroup()
                .addGroup(EmcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmcaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EmcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmcaLayout.createSequentialGroup()
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(EmcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EmcaLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EmcaLayout.createSequentialGroup()
                                .addGroup(EmcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EmcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EmcaLayout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addGap(30, 30, 30))))))
                    .addGroup(EmcaLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmcaLayout.setVerticalGroup(
            EmcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmcaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(EmcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmcaLayout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EmcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EmcaLayout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EmcaLayout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        panelCardLayout.add(Emca, "Emca");

        Eca.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/Eca.png"))); // NOI18N

        jSeparator4.setForeground(new java.awt.Color(164, 164, 164));

        jLabel7.setFont(new java.awt.Font("Rubik Light", 0, 36)); // NOI18N
        jLabel7.setText("Electrónica");

        jLabel27.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("<html>\n<h2>Áreas de desempeño laboral:</h2>\n</html>");

        jLabel28.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("<html> <ul>\n <li>Mantenimiento Electrónico.</li>\n <li>Mantenimiento Informático.</li>\n <li>Programador de sistemas PLC (Controlador lógico programable).</li> </ul> </html>");

        jLabel29.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("<html>\n<h2>Descripción:</h2>\n<p align=\"justify\">\nEl Bachiller Técnico en Electrónica, Es un profesional con conciencia crítica, analítica y reflexiva, con un alto sentido de autoformación, responsabilidad, autonomía y desarrollo empresarial. Es una persona emocionalmente madura con gran sensibilidad y capaz de interpretar la realidad nacional; es honesta, responsable y socialmente comprometida. Diseña sistemas sencillos, brinda asistencia técnica, mantenimiento preventivo y correctivo a sistemas electrónicos que se relacionan con el campo de la producción automatizada industrial, biomédica, sistemas informáticos personales, telecomunicaciones, audio y video.\n</p>\n</html>");

        jLabel30.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("<html>\n<h2>Título:</h2>\n<p align=\"justify\">\nBachiller técnico en Electrónica.\n</p>\n</html>");

        jLabel31.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("<html> <h2>Labororatorios Especializados:</h2> </html>");

        jLabel32.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("<html> <ul>\n <li>Laboratorio de Electrónica Análoga</li>\n <li>Laboratorio de Electrónica Digital</li>\n <li>Laboratorio de Telecomunicaciones</li>\n</ul> </html>");

        javax.swing.GroupLayout EcaLayout = new javax.swing.GroupLayout(Eca);
        Eca.setLayout(EcaLayout);
        EcaLayout.setHorizontalGroup(
            EcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(EcaLayout.createSequentialGroup()
                .addGroup(EcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EcaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(EcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EcaLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EcaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EcaLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(30, 30, 30))))
                    .addGroup(EcaLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EcaLayout.setVerticalGroup(
            EcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(EcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EcaLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(EcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EcaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EcaLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        panelCardLayout.add(Eca, "Eca");

        Diseño.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/Disenio.png"))); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(164, 164, 164));

        jLabel6.setFont(new java.awt.Font("Rubik Light", 0, 36)); // NOI18N
        jLabel6.setText("Diseño Gráfico");

        jLabel20.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("<html>\n<h2>Áreas de desempeño laboral:</h2>\n</html>");

        jLabel21.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("<html> <ul>\n <li>Diseñador gráfico.</li>\n <li>Arte finalista.</li>\n <li>Diseñador freelance</li> </ul> </html>");

        jLabel22.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("<html>\n<h2>Descripción:</h2>\n<p align=\"justify\">\nEl Bachiller Técnico vocacional en Diseño gráfico es capaz de desempeñarse en los procesos de conceptualización, interpretación y diseño de piezas gráficas con objetivos clave de comunicación. Se enfoca además en procesos de investigación, generación de ideas y fundamentos del diseño como parte principal para la ejecución de proyectos a nivel gráfico y el desarrollo de propuestas de estrategias de comunicación.\n</p>\n</html>");

        jLabel23.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("<html>\n<h2>Título:</h2>\n<p align=\"justify\">\nBachiller técnico en Diseño Gráfico.\n</p>\n</html>");

        jLabel24.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("<html> <h2>Labororatorios Especializados:</h2> </html>");

        jLabel25.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("<html> <ul>\n <li>Laboratorios de MAC. Laboratorios especializados para el trabajo de la especialidad de Diseño Gráfico que cuenta con software de diseño como lo es la suite de Adobe CS6.</li>\n</ul> </html>");

        javax.swing.GroupLayout DiseñoLayout = new javax.swing.GroupLayout(Diseño);
        Diseño.setLayout(DiseñoLayout);
        DiseñoLayout.setHorizontalGroup(
            DiseñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(DiseñoLayout.createSequentialGroup()
                .addGroup(DiseñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiseñoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(DiseñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DiseñoLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DiseñoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DiseñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(DiseñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DiseñoLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(30, 30, 30))))
                    .addGroup(DiseñoLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DiseñoLayout.setVerticalGroup(
            DiseñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiseñoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(DiseñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiseñoLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(DiseñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiseñoLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DiseñoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        panelCardLayout.add(Diseño, "Diseño");

        Software.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/Software.png"))); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(164, 164, 164));

        jLabel5.setFont(new java.awt.Font("Rubik Light", 0, 36)); // NOI18N
        jLabel5.setText("Desarrollo de Software");

        jLabel12.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("<html>\n<h2>Áreas de desempeño laboral:</h2>\n</html>");

        jLabel14.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("<html> <ul> <li>Analista de sistemas.</li> <li>Desarrollador de aseguramiento de calidad.</li> <li>Microempresario en el área de desarrollo web.</li> <li>Diseñador de sistemas y bases de datos.</li> <li>Arquitecto de sistemas.</li> <li>Instalador de redes LAN.</li> </ul> </html>");

        jLabel15.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("<html>\n<h2>Descripción:</h2>\n<p align=\"justify\">\nEl Bachiller Técnico en Desarrollo de Software, es un técnico de nivel medio, preparado para incorporarse a los procesos de desarrollo de aplicaciones de escritorio, intranet, web, dispositivos móviles, así como la creación y gestión de diversos tipos de bases de datos, y la instalación, configuración y mantenimiento de servidores, todo esto para aplicar adecuaciones o desarrollo de componentes de software en diversas áreas económicas y sociales en las cuales la cuantificación numérica de información, datos y la innovación es requerida.\n</p>\n</html>");

        jLabel16.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("<html>\n<h2>Título:</h2>\n<p align=\"justify\">\nBachiller técnico en Desarrollo de Software.\n</p>\n</html>");

        jLabel17.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("<html> <h2>Labororatorios Especializados:</h2> </html>");

        jLabel18.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("<html> <ul>\n <li>Laboratorios para desarrollo de software</li>\n <li>Área destinada a la programación y desarrollo de software con lenguajes de privativos u opensourse.</li>\n</ul> </html>");

        javax.swing.GroupLayout SoftwareLayout = new javax.swing.GroupLayout(Software);
        Software.setLayout(SoftwareLayout);
        SoftwareLayout.setHorizontalGroup(
            SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(SoftwareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SoftwareLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SoftwareLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SoftwareLayout.createSequentialGroup()
                        .addGroup(SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SoftwareLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(30, 30, 30)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SoftwareLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(191, 191, 191))
        );
        SoftwareLayout.setVerticalGroup(
            SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SoftwareLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SoftwareLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SoftwareLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SoftwareLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        panelCardLayout.add(Software, "Software");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModalActionPerformed
        cerrarDialog();
    }//GEN-LAST:event_btnCancelarModalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Arquitectura;
    private javax.swing.JPanel Auto;
    private javax.swing.JPanel Conta;
    private javax.swing.JPanel Diseño;
    private javax.swing.JPanel Eca;
    private javax.swing.JPanel Emca;
    private javax.swing.JPanel Itec;
    private javax.swing.JPanel Software;
    private javax.swing.JPanel TercerCiclo;
    private javax.swing.JButton btnCancelarModal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel panelCardLayout;
    // End of variables declaration//GEN-END:variables
}
