/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rexsdesktop.modal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import javax.imageio.ImageIO;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

import rexsdesktop.controller.Projects;
import static rexsdesktop.controller.Projects.getProject;
import rexsdesktop.controller.Validation;
import rexsdesktop.model.Db;
import rexsdesktop.view.Admin;

/**
 * Clase que contiene el Panel para visualizar y editar un proyecto.
 * @author Lulac
 */
public class ModalViewProyecto extends javax.swing.JPanel {

    /**
     * Creates new form ModalViewProyecto
     */
    public ModalViewProyecto() {
        initComponents();
        jcpNormal.getVerticalScrollBar().setPreferredSize(new Dimension(6, Integer.MAX_VALUE));
        jcpNormal.getVerticalScrollBar().setUnitIncrement(10);
        Db db = new Db();
        db.obtenerSeccionNivel();
        for(int i = 0; i < db.SNnivel.size(); i++) {
            combo.addItem(db.SNnivel.get(i) + " " + db.SNespecialidad.get(i) + " " + db.SNseccion.get(i));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlImg = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Img = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        jcpNormal = new javax.swing.JScrollPane();
        pnlView = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNivel = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JLabel();
        txtSeccion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lbl = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtUbiView = new javax.swing.JLabel();
        txtDescView = new javax.swing.JLabel();
        pnlPrueba = new javax.swing.JPanel();
        pnlContInte = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jlEdit1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jcpEdit = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        lblFotoPerfil = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        combo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(79, 54, 125));

        pnlImg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/002-left.png"))); // NOI18N
        pnlImg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 420));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/001-right.png"))); // NOI18N
        pnlImg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 50, 420));

        Img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/prueba3.jpg"))); // NOI18N
        pnlImg.add(Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 420));

        jScrollPane3.setBorder(null);

        jPanel6.setBackground(new java.awt.Color(201, 176, 245));
        jPanel6.setToolTipText("");
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 120, 100));

        jLabel8.setText("jLabel7");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 100));

        jLabel9.setText("jLabel7");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 100));

        jLabel10.setText("jLabel7");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 130, 100));

        jScrollPane3.setViewportView(jPanel6);

        pnlPrincipal.setLayout(new java.awt.CardLayout());

        jcpNormal.setBorder(null);

        pnlView.setBackground(new java.awt.Color(79, 54, 125));
        pnlView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(156, 117, 226));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNivel.setFont(new java.awt.Font("Rubik Medium",0,18));
        txtNivel.setForeground(new java.awt.Color(255, 255, 255));
        txtNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 34));

        txtEspecialidad.setFont(new java.awt.Font("Rubik Medium",0,18));
        txtEspecialidad.setForeground(new java.awt.Color(255, 255, 255));
        txtEspecialidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 110, 34));

        txtSeccion.setFont(new java.awt.Font("Rubik Medium",0,18));
        txtSeccion.setForeground(new java.awt.Color(255, 255, 255));
        txtSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 79, 34));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 10, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(4, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 10, 30));

        pnlView.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 410, 50));

        lbl.setEnabled(false);
        pnlView.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 508, -1, -1));

        txtNombre.setBackground(new java.awt.Color(79, 54, 125));
        txtNombre.setFont(new java.awt.Font("Rubik Bold",0,25) {
        }
    );
    txtNombre.setForeground(new java.awt.Color(255, 255, 255));
    pnlView.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 390, 60));

    jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
    pnlView.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 390, 10));

    jPanel4.setBackground(new java.awt.Color(156, 117, 226));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/project-management.png"))); // NOI18N

    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/exposition_1.png"))); // NOI18N

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/creativity.png"))); // NOI18N

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText(" Votación");

    jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(255, 255, 255));
    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel11.setText("Innovación");

    jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(255, 255, 255));
    jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel12.setText("Exposición");

    jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(255, 255, 255));
    jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel15.setText("Creatividad");

    jLabel16.setFont(new java.awt.Font("Comfortaa", 1, 18)); // NOI18N
    jLabel16.setForeground(new java.awt.Color(255, 255, 255));
    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel16.setText("9.6");

    jLabel17.setFont(new java.awt.Font("Comfortaa", 1, 18)); // NOI18N
    jLabel17.setForeground(new java.awt.Color(255, 255, 255));
    jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel17.setText("8.7");

    jLabel18.setFont(new java.awt.Font("Comfortaa", 1, 18)); // NOI18N
    jLabel18.setForeground(new java.awt.Color(255, 255, 255));
    jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel18.setText("8.0");

    jLabel19.setFont(new java.awt.Font("Comfortaa", 1, 18)); // NOI18N
    jLabel19.setForeground(new java.awt.Color(255, 255, 255));
    jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel19.setText("8.0");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))))
            .addGap(52, 52, 52)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addGap(37, 37, 37))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel1)
                .addComponent(jLabel3)
                .addComponent(jLabel5)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(44, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    pnlView.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 410, 170));

    jPanel5.setBackground(new java.awt.Color(156, 117, 226));

    jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel20.setForeground(new java.awt.Color(255, 255, 255));
    jLabel20.setText("Ubicación");

    txtUbiView.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    txtUbiView.setForeground(new java.awt.Color(255, 255, 255));
    txtUbiView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jLabel20)
                    .addGap(0, 337, Short.MAX_VALUE))
                .addComponent(txtUbiView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtUbiView, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(20, Short.MAX_VALUE))
    );

    pnlView.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 410, 100));

    txtDescView.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
    txtDescView.setForeground(new java.awt.Color(255, 255, 255));
    pnlView.add(txtDescView, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 390, 100));

    pnlPrueba.setBackground(new java.awt.Color(79, 54, 125));

    pnlContInte.setBackground(new java.awt.Color(156, 117, 226));

    jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel21.setForeground(new java.awt.Color(255, 255, 255));
    jLabel21.setText("Integrantes");

    javax.swing.GroupLayout pnlContInteLayout = new javax.swing.GroupLayout(pnlContInte);
    pnlContInte.setLayout(pnlContInteLayout);
    pnlContInteLayout.setHorizontalGroup(
        pnlContInteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlContInteLayout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel21)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnlContInteLayout.setVerticalGroup(
        pnlContInteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlContInteLayout.createSequentialGroup()
            .addGap(11, 11, 11)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(20, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout pnlPruebaLayout = new javax.swing.GroupLayout(pnlPrueba);
    pnlPrueba.setLayout(pnlPruebaLayout);
    pnlPruebaLayout.setHorizontalGroup(
        pnlPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pnlContInte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    pnlPruebaLayout.setVerticalGroup(
        pnlPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlPruebaLayout.createSequentialGroup()
            .addComponent(pnlContInte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(280, Short.MAX_VALUE))
    );

    pnlView.add(pnlPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 410, 330));

    jlEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/iconEditBlue.png"))); // NOI18N
    jlEdit1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jlEdit1MouseClicked(evt);
        }
    });
    pnlView.add(jlEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

    jButton4.setText("jButton4");
    pnlView.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 930, -1, -1));

    jcpNormal.setViewportView(pnlView);

    pnlPrincipal.add(jcpNormal, "card2");

    jcpEdit.setBorder(null);

    jPanel1.setBackground(new java.awt.Color(79, 54, 125));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel23.setBackground(new java.awt.Color(255, 255, 255));
    jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 193, 193)));
    jPanel23.setPreferredSize(new java.awt.Dimension(130, 130));
    jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/profilePicture.png"))); // NOI18N
    jPanel23.add(lblFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    jPanel1.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 339, -1, -1));

    txtnombre.setFont(new java.awt.Font("Rubik Bold",0,25) {
    }
    );
    jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 360, 56));

    txtDesc.setColumns(20);
    txtDesc.setFont(new java.awt.Font("Rubik Medium",0,15) {
    }
    );
    txtDesc.setLineWrap(true);
    txtDesc.setRows(5);
    jScrollPane1.setViewportView(txtDesc);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 106, 360, 140));

    combo.setBackground(new java.awt.Color(156, 117, 226));
    combo.setBorder(null);
    jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 264, 356, 40));

    jButton1.setBackground(new java.awt.Color(156, 117, 226));
    jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jButton1.setForeground(new java.awt.Color(255, 255, 255));
    jButton1.setText("Actualizar");
    jButton1.setBorder(null);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 511, 291, 48));

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Regresar");
    jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel2MouseClicked(evt);
        }
    });
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 60, -1));

    jButton2.setBackground(new java.awt.Color(156, 117, 226));
    jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 255));
    jButton2.setText("Agregar foto portada");
    jButton2.setBorder(null);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 140, 50));

    jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
    jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 410, 10));

    jcpEdit.setViewportView(jPanel1);

    pnlPrincipal.add(jcpEdit, "card3");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(pnlImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
            .addComponent(pnlImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Db obj = new Db();
        Projects panel = new Projects();
        String nombre = txtnombre.getText();
        String descripcion = txtDesc.getText();
        int idSeccionNivel = combo.getSelectedIndex() + 1;
        int id = Integer.parseInt(lbl.getText());
        if (!obj.proyectoExiste(nombre) || nombre.equals(nombre)) {
            if (Projects.actualizarPro(nombre, descripcion, idSeccionNivel, id)) {
                System.out.println("proyecto actualizado");
                Admin.cdProyectos.removeAll();
                panel.CrearPanelesProyectos(Admin.cdProyectos);
                Projects p = getProject(Integer.parseInt(lbl.getText()));
                txtDescView.setText(p.DescripcionP);
                txtEspecialidad.setText(p.EspecialidadP);
                txtSeccion.setText(p.SeccionP);
                txtNombre.setText("<html>" + p.nombreP + "</html>");
                txtnombre.setText(null);
                txtDesc.setText(null);
                pnlPrincipal.removeAll();
                pnlPrincipal.add(jcpNormal);
                pnlPrincipal.repaint();
                pnlPrincipal.revalidate();

            } else {
                System.out.println("Nel, falló");
            }
        } else {
            System.out.println("El proyecto ya existe");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        pnlPrincipal.removeAll();
        pnlPrincipal.add(jcpNormal);
        pnlPrincipal.repaint();
        pnlPrincipal.revalidate();    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fc = new JFileChooser();
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        fc.addChoosableFileFilter(imageFilter);
        fc.setAcceptAllFileFilterUsed(false);
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {

                File file = fc.getSelectedFile();
                if (Validation.VerificadorImagen.verifyFile(file)) {
                    FileInputStream fis = new FileInputStream(file);
                    BufferedImage imgOriginal = ImageIO.read(fis);
                    if (Validation.VerificadorImagen.verifyIMG(imgOriginal)) {
                        BufferedImage img = new BufferedImage(imgOriginal.getWidth(),
                                imgOriginal.getHeight(), BufferedImage.TYPE_INT_RGB);
                        img.createGraphics().drawImage(imgOriginal, 0, 0, Color.WHITE, null);
                        if (Projects.actualizarFotoPortada(img, Integer.parseInt(lbl.getText()))) {
                            JOptionPane.showMessageDialog(this, "Foto de perfil actualizada con éxito.", "Actualizar foto de perfil", JOptionPane.INFORMATION_MESSAGE);

                        } else {
                            JOptionPane.showMessageDialog(this, "Error al actualizar la foto de perfil.", "Actualizar foto de perfil", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, Validation.VerificadorImagen.mensaje, "Seleccionar imagen", JOptionPane.WARNING_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, Validation.VerificadorImagen.mensaje, "Seleccionar imagen", JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception ex) {
                System.out.println(ex);
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jlEdit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEdit1MouseClicked
        // TODO add your handling code here:
         pnlPrincipal.removeAll();
        pnlPrincipal.add(jcpEdit);
        pnlPrincipal.repaint();
        pnlPrincipal.revalidate();
    }//GEN-LAST:event_jlEdit1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Img;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JScrollPane jcpEdit;
    private javax.swing.JScrollPane jcpNormal;
    private javax.swing.JLabel jlEdit1;
    public javax.swing.JLabel lbl;
    private javax.swing.JLabel lblFotoPerfil;
    public static javax.swing.JPanel pnlContInte;
    private javax.swing.JPanel pnlImg;
    private javax.swing.JPanel pnlPrincipal;
    public static javax.swing.JPanel pnlPrueba;
    private javax.swing.JPanel pnlView;
    public javax.swing.JTextArea txtDesc;
    public javax.swing.JLabel txtDescView;
    public javax.swing.JLabel txtEspecialidad;
    public javax.swing.JLabel txtNivel;
    public javax.swing.JLabel txtNombre;
    public javax.swing.JLabel txtSeccion;
    public javax.swing.JLabel txtUbiView;
    public javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

}
