/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rexsdesktop.modal;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import rexsdesktop.controller.Sections;
import rexsdesktop.controller.User;
import rexsdesktop.model.DbConnection;

/**
 * Clase que contiene el Panel para modificar una sección.
 * @author artur
 */
public class ModalModificarSecciones extends javax.swing.JPanel {

    /**
     * Creates new form ModalModificarSecciones
     */
    DefaultTableModel modelo = new DefaultTableModel();

    public ModalModificarSecciones() {
        initComponents();
        Sections Conexion = new Sections();
        cbxEspecialidadModal.setModel(Conexion.obtenerEspecialidad());
        cbxUbicacionModal.setModel(Conexion.obtenerUbicacion());
        cbxNivelModal.setModel(Conexion.obtenerNivel());
        //Tabla
        String[] titulo = new String[]{"Id", "Seccion", "Nivel", "Especialidad", "Ubicacion"};
        modelo.setColumnIdentifiers(titulo);
        jTTabla.setModel(modelo);
        cargarProyectos();
        //Enviar datos de tabla txt
        jTTabla.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    txtIdModal.setText(jTTabla.getValueAt(jTTabla.getSelectedRow(), 0).toString());
                    cbxNivelModal.setSelectedItem(jTTabla.getValueAt(jTTabla.getSelectedRow(), 2));
                    cbxEspecialidadModal.setSelectedItem(jTTabla.getValueAt(jTTabla.getSelectedRow(), 3));
                    cbxUbicacionModal.setSelectedItem(jTTabla.getValueAt(jTTabla.getSelectedRow(), 4));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel67 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        btnModificarSeccionModal = new javax.swing.JButton();
        cbxUbicacionModal = new javax.swing.JComboBox<>();
        jLabel93 = new javax.swing.JLabel();
        txtSeccionModal = new javax.swing.JTextField();
        jLabel91 = new javax.swing.JLabel();
        cbxNivelModal = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        cbxEspecialidadModal = new javax.swing.JComboBox<>();
        btnCancelarModal = new javax.swing.JButton();
        btnEliminarSeccionModal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabla = new javax.swing.JTable();
        jLabel68 = new javax.swing.JLabel();
        txtIdModal = new javax.swing.JTextField();

        jLabel67.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(176, 186, 201));
        jLabel67.setText("SECCION");

        jLabel92.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(176, 186, 201));
        jLabel92.setText("ESPECIALIDAD");

        btnModificarSeccionModal.setBackground(new java.awt.Color(213, 222, 255));
        btnModificarSeccionModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnModificarSeccionModal.setForeground(new java.awt.Color(46, 91, 255));
        btnModificarSeccionModal.setText("Modificar");
        btnModificarSeccionModal.setBorderPainted(false);
        btnModificarSeccionModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarSeccionModalActionPerformed(evt);
            }
        });

        cbxUbicacionModal.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        cbxUbicacionModal.setForeground(new java.awt.Color(46, 56, 77));
        cbxUbicacionModal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel93.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(176, 186, 201));
        jLabel93.setText("UBICACION");

        txtSeccionModal.setBackground(new java.awt.Color(249, 250, 255));
        txtSeccionModal.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        txtSeccionModal.setForeground(new java.awt.Color(46, 56, 77));
        txtSeccionModal.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));

        jLabel91.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(176, 186, 201));
        jLabel91.setText("NIVEL");

        cbxNivelModal.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        cbxNivelModal.setForeground(new java.awt.Color(46, 56, 77));
        cbxNivelModal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNivelModal.setPreferredSize(new java.awt.Dimension(56, 27));

        jSeparator1.setForeground(new java.awt.Color(164, 164, 164));

        cbxEspecialidadModal.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        cbxEspecialidadModal.setForeground(new java.awt.Color(46, 56, 77));
        cbxEspecialidadModal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelarModal.setBackground(new java.awt.Color(247, 214, 218));
        btnCancelarModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnCancelarModal.setForeground(new java.awt.Color(214, 54, 73));
        btnCancelarModal.setText("Cancelar");
        btnCancelarModal.setBorderPainted(false);

        btnEliminarSeccionModal.setBackground(new java.awt.Color(213, 222, 255));
        btnEliminarSeccionModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnEliminarSeccionModal.setForeground(new java.awt.Color(46, 91, 255));
        btnEliminarSeccionModal.setText("Eliminar");
        btnEliminarSeccionModal.setBorderPainted(false);
        btnEliminarSeccionModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSeccionModalActionPerformed(evt);
            }
        });

        jTTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTTabla);

        jLabel68.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(176, 186, 201));
        jLabel68.setText("ID");

        txtIdModal.setBackground(new java.awt.Color(249, 250, 255));
        txtIdModal.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        txtIdModal.setForeground(new java.awt.Color(46, 56, 77));
        txtIdModal.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel67, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel91)
                                        .addComponent(cbxNivelModal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(15, 15, 15)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel92)
                                        .addComponent(cbxEspecialidadModal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel93)
                                .addComponent(cbxUbicacionModal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtSeccionModal, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel68)
                            .addComponent(txtIdModal)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminarSeccionModal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarSeccionModal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(jLabel68))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeccionModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel91)
                            .addGap(1, 1, 1)
                            .addComponent(cbxNivelModal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel92)
                            .addGap(1, 1, 1)
                            .addComponent(cbxEspecialidadModal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel93)
                        .addGap(1, 1, 1)
                        .addComponent(cbxUbicacionModal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarSeccionModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarSeccionModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cargarProyectos() {
        DbConnection cone = new DbConnection();
        Connection con = cone.conectar();
        try {
            Statement stm = con.createStatement();
            ResultSet rst = stm.executeQuery("select idSeccionNivel, seccion, nivel, especialidad, ubicacion FROM seccionNivel,nivel, especialidad, ubicacion where seccionNivel.idNivel = nivel.idNivel and seccionNivel.idEspecialidad = especialidad.idEspecialidad and seccionNivel.idUbicacion = ubicacion.idUbicacion");
            while (rst.next()) {
                modelo.addRow(new Object[]{
                    rst.getInt(1),
                    rst.getString(2),
                    rst.getString(3),
                    rst.getString(4),
                    rst.getString(5),});
            }
        } catch (Exception e) {
        }
    }

    private void btnModificarSeccionModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarSeccionModalActionPerformed
        Sections Conexion = new Sections();
        //JOptionPane.showMessageDialog(null, String.valueOf(jComboBox1.getSelectedIndex() + 1));

        try {

            Conexion.setSeccion(txtSeccionModal.getText());
            Conexion.setIdNivel(cbxNivelModal.getSelectedIndex());
            Conexion.setIdEspecialidad(cbxEspecialidadModal.getSelectedIndex());
            Conexion.setIdUbicacion(cbxUbicacionModal.getSelectedIndex());
            Conexion.setIdSeccion(Integer.parseInt(txtIdModal.getText()));
            if (Conexion.ActualizarSeccion()) {
                JOptionPane.showMessageDialog(null, "Datos modificados correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Error al modficar datos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR GLOBAL");
        }
    }//GEN-LAST:event_btnModificarSeccionModalActionPerformed

    private void btnEliminarSeccionModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSeccionModalActionPerformed
        // TODO add your handling code here:
        Sections Conexion = new Sections();
        try {
            Conexion.setIdSeccion(Integer.parseInt(txtIdModal.getText()));
            if (Conexion.ElminarSeccion()) {
                JOptionPane.showMessageDialog(null, "Sección eliminada");
                //limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar sección");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR GLOBAL");
        }
    }//GEN-LAST:event_btnEliminarSeccionModalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarModal;
    private javax.swing.JButton btnEliminarSeccionModal;
    private javax.swing.JButton btnModificarSeccionModal;
    private javax.swing.JComboBox<String> cbxEspecialidadModal;
    private javax.swing.JComboBox<String> cbxNivelModal;
    private javax.swing.JComboBox<String> cbxUbicacionModal;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTTabla;
    private javax.swing.JTextField txtIdModal;
    private javax.swing.JTextField txtSeccionModal;
    // End of variables declaration//GEN-END:variables
}
