/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rexsdesktop.modal;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import rexsdesktop.controller.Sections;
import rexsdesktop.model.DbConnection;

/**
 * Clase que contiene el Panel para modificar una especialidad.
 * @author artur
 */
public class ModalModificarEspecialidad extends javax.swing.JPanel {

    /**
     * Creates new form ModalModificarEspecialidad
     */
    DefaultTableModel modelo = new DefaultTableModel();
    public ModalModificarEspecialidad() {
        initComponents();
        //Tabla
        String[] titulo = new String[]{"Id", "Especialidad"};
        modelo.setColumnIdentifiers(titulo);
        jTTabla.setModel(modelo);
        cargarTabla();
        //Enviar datos de tabla txt
        jTTabla.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    txtEspecialidadId.setText(jTTabla.getValueAt(jTTabla.getSelectedRow(), 0).toString());
                    txtEspecialidadModal.setText(jTTabla.getValueAt(jTTabla.getSelectedRow(), 1).toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelarModal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel67 = new javax.swing.JLabel();
        txtEspecialidadModal = new javax.swing.JTextField();
        btnModificarModal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabla = new javax.swing.JTable();
        idTipo = new javax.swing.JLabel();
        txtEspecialidadId = new javax.swing.JTextField();
        btnEliminarModal = new javax.swing.JButton();

        btnCancelarModal.setBackground(new java.awt.Color(247, 214, 218));
        btnCancelarModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnCancelarModal.setForeground(new java.awt.Color(214, 54, 73));
        btnCancelarModal.setText("Cancelar");
        btnCancelarModal.setBorderPainted(false);

        jSeparator1.setForeground(new java.awt.Color(164, 164, 164));

        jLabel67.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(176, 186, 201));
        jLabel67.setText("Especialidad");

        txtEspecialidadModal.setBackground(new java.awt.Color(249, 250, 255));
        txtEspecialidadModal.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        txtEspecialidadModal.setForeground(new java.awt.Color(46, 56, 77));
        txtEspecialidadModal.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));

        btnModificarModal.setBackground(new java.awt.Color(213, 222, 255));
        btnModificarModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnModificarModal.setForeground(new java.awt.Color(46, 91, 255));
        btnModificarModal.setText("Modficar");
        btnModificarModal.setBorderPainted(false);
        btnModificarModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarModalActionPerformed(evt);
            }
        });

        jTTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTTabla);

        idTipo.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        idTipo.setForeground(new java.awt.Color(176, 186, 201));
        idTipo.setText("ID");

        txtEspecialidadId.setBackground(new java.awt.Color(249, 250, 255));
        txtEspecialidadId.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        txtEspecialidadId.setForeground(new java.awt.Color(46, 56, 77));
        txtEspecialidadId.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));

        btnEliminarModal.setBackground(new java.awt.Color(213, 222, 255));
        btnEliminarModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnEliminarModal.setForeground(new java.awt.Color(46, 91, 255));
        btnEliminarModal.setText("Eliminar");
        btnEliminarModal.setBorderPainted(false);
        btnEliminarModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarModalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEliminarModal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarModal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarModal))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel67)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEspecialidadModal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEspecialidadId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTipo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel67)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEspecialidadModal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspecialidadId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
   
    
    public void cargarTabla() {
        DbConnection cone = new DbConnection();
        Connection con = cone.conectar();
        try {
            Statement stm = con.createStatement();
            ResultSet rst = stm.executeQuery("select idEspecialidad, especialidad from especialidad");
            while (rst.next()) {
                modelo.addRow(new Object[]{
                    rst.getInt(1),
                    rst.getString(2),});
            }
        } catch (Exception e) {
        }
    }
    private void btnModificarModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarModalActionPerformed
        Sections Conexion = new Sections();
        //JOptionPane.showMessageDialog(null, String.valueOf(jComboBox1.getSelectedIndex() + 1));

        try {

            Conexion.setEspecialidad(txtEspecialidadModal.getText());
            Conexion.setIdEspecialidad(Integer.parseInt(txtEspecialidadId.getText()));
            jTTabla.setModel(modelo);
            if (Conexion.ActualizarEspecialidad()) {
                JOptionPane.showMessageDialog(null, "Datos modficados correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Error al modficar datos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR GLOBAL");
        }
    }//GEN-LAST:event_btnModificarModalActionPerformed

    private void btnEliminarModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarModalActionPerformed
        // TODO add your handling code here:
        Sections Conexion = new Sections();
        try {
            Conexion.setIdEspecialidad(Integer.parseInt(txtEspecialidadId.getText()));
            if (Conexion.ElminarEspecialidad()) {
                JOptionPane.showMessageDialog(null, "Especialidad Eliminada");
                //limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar especialidad");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR GLOBAL");
        }
    }//GEN-LAST:event_btnEliminarModalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarModal;
    private javax.swing.JButton btnEliminarModal;
    private javax.swing.JButton btnModificarModal;
    private javax.swing.JLabel idTipo;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTTabla;
    private javax.swing.JTextField txtEspecialidadId;
    private javax.swing.JTextField txtEspecialidadModal;
    // End of variables declaration//GEN-END:variables
}
