/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rexsdesktop.modal;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import rexsdesktop.CurrentUser;
import rexsdesktop.controller.Projects;
import rexsdesktop.controller.User;
import rexsdesktop.controller.Validation;
import rexsdesktop.model.Db;
import rexsdesktop.view.Admin;

/**
 * Clase que contiene el Panel para agregar un nuevo proyecto.
 * @author Lulac
 */
public class ModalNuevoProyecto extends javax.swing.JPanel {

    /**
     * Creates new form ModalNuevoProyecto
     */
    public ModalNuevoProyecto() {
        initComponents();
        Db db = new Db();

        db.obtenerSeccionNivel();

        for (int i = 0; i < db.SNnivel.size(); i++) {
            cbxSeccionNivel.addItem(db.SNnivel.get(i) + " " + db.SNespecialidad.get(i) + " " + db.SNseccion.get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel65 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txtnombreProyecto = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        btnCambiarFotoPro = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAceptarModal = new javax.swing.JButton();
        btnCancelarModal = new javax.swing.JButton();
        cbxSeccionNivel = new javax.swing.JComboBox<>();
        jLabel70 = new javax.swing.JLabel();

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/profilePicture.png"))); // NOI18N
        jLabel65.setToolTipText("Foto del proyecto");

        jLabel67.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(176, 186, 201));
        jLabel67.setText("NOMBRE DEL PROYECTO");

        txtnombreProyecto.setBackground(new java.awt.Color(249, 250, 255));
        txtnombreProyecto.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        txtnombreProyecto.setForeground(new java.awt.Color(46, 56, 77));
        txtnombreProyecto.setToolTipText("Nombre del nuevo proyecto");
        txtnombreProyecto.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));

        jLabel69.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(176, 186, 201));
        jLabel69.setText("DESCRIPCIÓN");

        txtDesc.setBackground(new java.awt.Color(249, 250, 255));
        txtDesc.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        txtDesc.setForeground(new java.awt.Color(46, 56, 77));
        txtDesc.setToolTipText("Descripción del nuevo proyecto");
        txtDesc.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 231, 255), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15)));

        btnCambiarFotoPro.setBackground(new java.awt.Color(238, 238, 238));
        btnCambiarFotoPro.setFont(new java.awt.Font("Rubik", 0, 10)); // NOI18N
        btnCambiarFotoPro.setForeground(new java.awt.Color(107, 107, 107));
        btnCambiarFotoPro.setText("Cambiar Foto");
        btnCambiarFotoPro.setToolTipText("Cambiar foto por defecto");
        btnCambiarFotoPro.setBorderPainted(false);
        btnCambiarFotoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarFotoProActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(238, 238, 238));
        jButton4.setFont(new java.awt.Font("Rubik", 0, 10)); // NOI18N
        jButton4.setForeground(new java.awt.Color(107, 107, 107));
        jButton4.setText("Eliminar Foto");
        jButton4.setToolTipText("Eliminar foto");
        jButton4.setBorderPainted(false);

        jSeparator1.setForeground(new java.awt.Color(164, 164, 164));

        btnAceptarModal.setBackground(new java.awt.Color(213, 222, 255));
        btnAceptarModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnAceptarModal.setForeground(new java.awt.Color(46, 91, 255));
        btnAceptarModal.setText("Aceptar");
        btnAceptarModal.setToolTipText("Ingresar un nuevo proyecto");
        btnAceptarModal.setBorderPainted(false);
        btnAceptarModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarModalActionPerformed(evt);
            }
        });

        btnCancelarModal.setBackground(new java.awt.Color(247, 214, 218));
        btnCancelarModal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        btnCancelarModal.setForeground(new java.awt.Color(214, 54, 73));
        btnCancelarModal.setText("Cancelar");
        btnCancelarModal.setBorderPainted(false);
        btnCancelarModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModalActionPerformed(evt);
            }
        });

        cbxSeccionNivel.setFont(new java.awt.Font("Rubik", 0, 11)); // NOI18N
        cbxSeccionNivel.setForeground(new java.awt.Color(46, 56, 77));
        cbxSeccionNivel.setToolTipText("Sección y nivel del nuevo proyecto");
        cbxSeccionNivel.setPreferredSize(new java.awt.Dimension(56, 27));
        cbxSeccionNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeccionNivelActionPerformed(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Rubik Medium", 0, 10)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(176, 186, 201));
        jLabel70.setText("SECCION NIVEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCambiarFotoPro)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel65))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel67)
                    .addComponent(jLabel69)
                    .addComponent(txtDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(txtnombreProyecto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel70)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSeccionNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAceptarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCambiarFotoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel67)
                        .addGap(1, 1, 1)
                        .addComponent(txtnombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel69)
                        .addGap(1, 1, 1)
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSeccionNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel70))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarModalActionPerformed
        Db obj = new Db();
        Projects panel = new Projects();
        String nombre = txtnombreProyecto.getText();
        String descripcion = txtDesc.getText();
        int idSeccionNivel = cbxSeccionNivel.getSelectedIndex() + 1;
        if (!obj.proyectoExiste(nombre)) {
            if (Projects.nuevoProyecto(nombre, descripcion, idSeccionNivel)) {
                System.out.println("proyecto Ingresada");
                txtnombreProyecto.setText(null);
                txtDesc.setText(null);
                Admin.cdProyectos.removeAll();
                panel.CrearPanelesProyectos(Admin.cdProyectos);
            } else {
                System.out.println("Nel, falló");
            }
        } else {
            System.out.println("El proyecto ya existe");
        }


    }//GEN-LAST:event_btnAceptarModalActionPerformed

    private void cbxSeccionNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeccionNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSeccionNivelActionPerformed

    private void btnCambiarFotoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarFotoProActionPerformed

    }//GEN-LAST:event_btnCambiarFotoProActionPerformed

    private void btnCancelarModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarModalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarModal;
    private javax.swing.JButton btnCambiarFotoPro;
    private javax.swing.JButton btnCancelarModal;
    private javax.swing.JComboBox<String> cbxSeccionNivel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtnombreProyecto;
    // End of variables declaration//GEN-END:variables
}
