/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rexsdesktop.modal;

import java.awt.Desktop;
import java.awt.Dimension;
import java.net.URI;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import rexsdesktop.CurrentUser;
import rexsdesktop.controller.Locations;
import rexsdesktop.controller.Projects;
import static rexsdesktop.controller.Projects.getNumIMG;
import rexsdesktop.controller.Votes;
import rexsdesktop.model.Db;

/**
 * Clase que contiene el Panel para visualizar y editar un proyecto.
 *
 * @author Lulac
 */
public class ModalViewProyectoPoint extends javax.swing.JPanel {

    public static int idProyecto;
    public String idUbicacion;
    int contador = 0;

    /**
     * Creates new form ModalViewProyecto
     */
    public ModalViewProyectoPoint() {
        initComponents();
        jcpNormal.getVerticalScrollBar().setPreferredSize(new Dimension(6, Integer.MAX_VALUE));
        jcpNormal.getVerticalScrollBar().setUnitIncrement(10);
        criterio1.setMinimum(1);
        criterio2.setMinimum(1);
        criterio3.setMinimum(1);
        criterio1.setMaximum(10);
        criterio2.setMaximum(10);
        criterio3.setMaximum(10);
        lblPuntajeFinal.setVisible(false);
        jLabel14.setEnabled(false);
        if (CurrentUser.idUsuario != 0) {
            if (Votes.existeVoto(CurrentUser.idUsuario, idProyecto)) {
                yaExiste();
            }
        }
        else{
            pnlVotacion.setVisible(false);
        }

    }

    private void yaExiste() {
        btnVotar.setEnabled(false);
        criterio1.setEnabled(false);
        criterio2.setEnabled(false);
        criterio3.setEnabled(false);
        lblPuntajeFinal.setVisible(true);
        lblPuntajeFinal.setText("Puntaje final: " + String.valueOf(Votes.getPromedioFinalVoto(CurrentUser.idUsuario, idProyecto)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlImg = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Img = new javax.swing.JLabel();
        pnlViewImagenes = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        jcpNormal = new javax.swing.JScrollPane();
        pnlView = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        txtDescView = new javax.swing.JLabel();
        txtNivel = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JLabel();
        txtSeccion = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlVotos = new javax.swing.JPanel();
        stars = new javax.swing.JLabel();
        NumExpo = new javax.swing.JLabel();
        NumInnovacion = new javax.swing.JLabel();
        NumCreatividad = new javax.swing.JLabel();
        txtPromVoto = new javax.swing.JLabel();
        Exposicion = new javax.swing.JLabel();
        Creatividad = new javax.swing.JLabel();
        Innovacion = new javax.swing.JLabel();
        txtNumVotos = new javax.swing.JLabel();
        Separator2 = new javax.swing.JSeparator();
        pnlUbicacion = new javax.swing.JPanel();
        btnVerMapa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jlPoint = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUbiView = new javax.swing.JLabel();
        jlMapa = new javax.swing.JLabel();
        pnlViewIntegrantes = new javax.swing.JPanel();
        lb = new javax.swing.JLabel();
        dot1 = new javax.swing.JLabel();
        dot2 = new javax.swing.JLabel();
        pnlVotacion = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        criterio2 = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        criterio3 = new javax.swing.JSlider();
        btnVotar = new javax.swing.JButton();
        lblCriterio1 = new javax.swing.JLabel();
        lblCriterio2 = new javax.swing.JLabel();
        lblCriterio3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        criterio1 = new javax.swing.JSlider();
        lblPuntajeFinal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 246, 252));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(896, 586));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlImg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/002-left.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        pnlImg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 420));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/001-right.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        pnlImg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 50, 420));

        Img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/zz.png"))); // NOI18N
        pnlImg.add(Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 420));

        add(pnlImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlViewImagenes.setBackground(new java.awt.Color(244, 246, 252));

        javax.swing.GroupLayout pnlViewImagenesLayout = new javax.swing.GroupLayout(pnlViewImagenes);
        pnlViewImagenes.setLayout(pnlViewImagenesLayout);
        pnlViewImagenesLayout.setHorizontalGroup(
            pnlViewImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        pnlViewImagenesLayout.setVerticalGroup(
            pnlViewImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        add(pnlViewImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 420, 140));

        pnlPrincipal.setLayout(new java.awt.CardLayout());

        jcpNormal.setBorder(null);
        jcpNormal.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlView.setBackground(new java.awt.Color(244, 246, 252));
        pnlView.setMinimumSize(new java.awt.Dimension(442, 586));

        txtNombre.setBackground(new java.awt.Color(79, 54, 125));
        txtNombre.setFont(new java.awt.Font("Rubik Ligth",0,29)
        );
        txtNombre.setForeground(new java.awt.Color(46, 56, 77));
        txtNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtNombre.setToolTipText("");
        txtNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtNombre.setIconTextGap(0);

        txtDescView.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        txtDescView.setForeground(new java.awt.Color(136, 136, 136));
        txtDescView.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtNivel.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        txtNivel.setForeground(new java.awt.Color(135, 152, 173));
        txtNivel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtEspecialidad.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        txtEspecialidad.setForeground(new java.awt.Color(135, 152, 173));
        txtEspecialidad.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtSeccion.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        txtSeccion.setForeground(new java.awt.Color(135, 152, 173));
        txtSeccion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        id.setBackground(new java.awt.Color(244, 246, 252));
        id.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        id.setForeground(new java.awt.Color(244, 246, 252));
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setForeground(new java.awt.Color(221, 221, 221));
        jSeparator1.setPreferredSize(new java.awt.Dimension(70, 20));

        pnlVotos.setBackground(new java.awt.Color(255, 255, 255));

        stars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/stars.png"))); // NOI18N

        NumExpo.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        NumExpo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumExpo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/1.png"))); // NOI18N
        NumExpo.setText("9.8");
        NumExpo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        NumInnovacion.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        NumInnovacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumInnovacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/1.png"))); // NOI18N
        NumInnovacion.setText("7.0");
        NumInnovacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        NumCreatividad.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        NumCreatividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumCreatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/1.png"))); // NOI18N
        NumCreatividad.setText("8.9");
        NumCreatividad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtPromVoto.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        txtPromVoto.setText("8.9");

        Exposicion.setFont(new java.awt.Font("Rubik Light", 0, 12)); // NOI18N
        Exposicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exposicion.setText("Exposición");
        Exposicion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Creatividad.setFont(new java.awt.Font("Rubik Light", 0, 12)); // NOI18N
        Creatividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Creatividad.setText("Creatividad");
        Creatividad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Innovacion.setFont(new java.awt.Font("Rubik Light", 0, 12)); // NOI18N
        Innovacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Innovacion.setText("Innovación");
        Innovacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtNumVotos.setFont(new java.awt.Font("Rubik", 0, 13)); // NOI18N
        txtNumVotos.setForeground(new java.awt.Color(136, 136, 136));
        txtNumVotos.setText("+100 votos");

        Separator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout pnlVotosLayout = new javax.swing.GroupLayout(pnlVotos);
        pnlVotos.setLayout(pnlVotosLayout);
        pnlVotosLayout.setHorizontalGroup(
            pnlVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVotosLayout.createSequentialGroup()
                .addGroup(pnlVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVotosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtPromVoto)
                        .addGap(6, 6, 6)
                        .addComponent(txtNumVotos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVotosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stars)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVotosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Creatividad))
                    .addGroup(pnlVotosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(NumCreatividad)))
                .addGap(2, 2, 2)
                .addGroup(pnlVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVotosLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(NumInnovacion)
                        .addGap(43, 43, 43)
                        .addComponent(NumExpo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlVotosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Innovacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Exposicion)
                        .addGap(22, 22, 22))))
        );
        pnlVotosLayout.setVerticalGroup(
            pnlVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVotosLayout.createSequentialGroup()
                .addGroup(pnlVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVotosLayout.createSequentialGroup()
                        .addGroup(pnlVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVotosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NumInnovacion)
                                    .addComponent(NumExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumCreatividad))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNumVotos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPromVoto, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stars)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVotosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Separator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVotosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Creatividad)
                                    .addComponent(Innovacion)
                                    .addComponent(Exposicion))))))
                .addContainerGap())
        );

        pnlUbicacion.setBackground(new java.awt.Color(255, 255, 255));
        pnlUbicacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerMapa.setBackground(new java.awt.Color(46, 91, 255));
        btnVerMapa.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        btnVerMapa.setForeground(new java.awt.Color(255, 255, 255));
        btnVerMapa.setText("Ver en mapa");
        btnVerMapa.setToolTipText("Iniciar sesión");
        btnVerMapa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnVerMapa.setBorderPainted(false);
        btnVerMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMapaActionPerformed(evt);
            }
        });
        pnlUbicacion.add(btnVerMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 96, 26));

        jLabel5.setFont(new java.awt.Font("Rubik Light", 0, 12)); // NOI18N
        jLabel5.setText("Ubicación");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlUbicacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 90, 20));

        jlPoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/Point.png"))); // NOI18N
        pnlUbicacion.add(jlPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 40));

        jLabel3.setFont(new java.awt.Font("Rubik Light", 0, 12)); // NOI18N
        jLabel3.setText("Encuentralo en:");
        pnlUbicacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 20));

        txtUbiView.setBackground(new java.awt.Color(255, 255, 255));
        txtUbiView.setFont(new java.awt.Font("Rubik Medium", 0, 18)); // NOI18N
        txtUbiView.setForeground(new java.awt.Color(34, 34, 34));
        txtUbiView.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUbiView.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlUbicacion.add(txtUbiView, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 240, 30));

        jlMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/map img.png"))); // NOI18N
        pnlUbicacion.add(jlMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 140));

        pnlViewIntegrantes.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlViewIntegrantesLayout = new javax.swing.GroupLayout(pnlViewIntegrantes);
        pnlViewIntegrantes.setLayout(pnlViewIntegrantesLayout);
        pnlViewIntegrantesLayout.setHorizontalGroup(
            pnlViewIntegrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlViewIntegrantesLayout.setVerticalGroup(
            pnlViewIntegrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        lb.setFont(new java.awt.Font("Rubik", 0, 13)); // NOI18N
        lb.setText("DESCRIPCIÓN");

        dot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/dot.png"))); // NOI18N

        dot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rexsdesktop/view/resources/dot.png"))); // NOI18N

        jLabel15.setText("Exposición");

        jLabel16.setText("Creatividad");

        criterio2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                criterio2StateChanged(evt);
            }
        });

        jLabel17.setText("Innovación");

        criterio3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                criterio3StateChanged(evt);
            }
        });

        btnVotar.setBackground(new java.awt.Color(46, 91, 255));
        btnVotar.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        btnVotar.setForeground(new java.awt.Color(255, 255, 255));
        btnVotar.setText("Votar");
        btnVotar.setToolTipText("Iniciar sesión");
        btnVotar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnVotar.setBorderPainted(false);
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });

        lblCriterio1.setText("8.0");

        lblCriterio2.setText("9.0");

        lblCriterio3.setText("9.0");

        jLabel12.setText("Votación");

        criterio1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                criterio1StateChanged(evt);
            }
        });

        lblPuntajeFinal.setFont(new java.awt.Font("Rubik Medium", 0, 11)); // NOI18N
        lblPuntajeFinal.setText("Puntaje final: 9.0");

        javax.swing.GroupLayout pnlVotacionLayout = new javax.swing.GroupLayout(pnlVotacion);
        pnlVotacion.setLayout(pnlVotacionLayout);
        pnlVotacionLayout.setHorizontalGroup(
            pnlVotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVotacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVotacionLayout.createSequentialGroup()
                        .addGroup(pnlVotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVotacionLayout.createSequentialGroup()
                                .addComponent(criterio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCriterio1))
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addGroup(pnlVotacionLayout.createSequentialGroup()
                                .addComponent(criterio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCriterio3))
                            .addComponent(jLabel17)
                            .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlVotacionLayout.createSequentialGroup()
                        .addComponent(criterio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCriterio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPuntajeFinal)
                        .addGap(32, 32, 32))))
        );
        pnlVotacionLayout.setVerticalGroup(
            pnlVotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVotacionLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addGap(2, 2, 2)
                .addGroup(pnlVotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCriterio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(criterio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGroup(pnlVotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVotacionLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(criterio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCriterio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPuntajeFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGroup(pnlVotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVotacionLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(criterio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCriterio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb)
                            .addGroup(pnlViewLayout.createSequentialGroup()
                                .addComponent(txtNivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dot1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEspecialidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dot2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(txtSeccion)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(328, 328, 328))
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlViewIntegrantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescView, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlUbicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlVotacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dot1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dot2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescView)
                .addGap(27, 27, 27)
                .addComponent(pnlVotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlViewIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pnlUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jcpNormal.setViewportView(pnlView);

        pnlPrincipal.add(jcpNormal, "card2");

        add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 0, 450, 586));
    }// </editor-fold>//GEN-END:initComponents


    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        Db db = new Db();
        Projects p = new Projects();
        Projects t = getNumIMG(Integer.parseInt(id.getText()));
        db.getIMGresources(Integer.parseInt(id.getText()));
        if (t.CountIMGresources != 0) {
            if (contador + 1 < t.CountIMGresources) {
                if (contador + 1 == t.CountIMGresources) {
                    contador = 0;
                }
                contador++;
                System.out.println("Aqui " + contador);
                jLabel14.enable();
                Img.setIcon(new ImageIcon(db.RecImagenes.get(contador)));
            }

        } else {
            JOptionPane.showMessageDialog(this, "No hay imágenes disponibles en este proyecto.");
        }


    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if (jLabel14.isEnabled()) {
            Db db = new Db();
            Projects p = new Projects();
            Projects t = getNumIMG(Integer.parseInt(id.getText()));
            db.getIMGresources(Integer.parseInt(id.getText()));
            if (t.CountIMGresources != 0) {
                if (contador < t.CountIMGresources) {
                    if (contador == 0) {
                        contador = t.CountIMGresources;
                    }
                    contador--;
                    System.out.println("Aqui " + contador);
                    if (contador >= 0) {
                        Img.setIcon(new ImageIcon(db.RecImagenes.get(contador)));
                    }

                }

            } else {
                JOptionPane.showMessageDialog(this, "No hay imágenes disponibles en este proyecto.");
            }
        }


    }//GEN-LAST:event_jLabel14MouseClicked

    private void btnVerMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMapaActionPerformed
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
            String alias = Locations.getAlias(idUbicacion);
            try {
                Desktop.getDesktop().browse(new URI("https://maps.mapwize.io/#/p/ITR/" + alias + "?k=be2e22efcc70dfb3&embed=true&menu=false&venueId=5c8ef893f9e6100016da65ac&organizationId=5c8ef687f9e6100016da6590&z=19"));
            } catch (Exception ex) {
                System.out.println("Open map in web browser error: " + ex.getMessage());
            }
        }
        //
    }//GEN-LAST:event_btnVerMapaActionPerformed

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        List<Object> criterioExpo = new Vector<Object>();
        criterioExpo.add((double) criterio1.getValue());
        criterioExpo.add("Exposición");

        List<Object> criterioCreatividad = new Vector<Object>();
        criterioCreatividad.add((double) criterio2.getValue());
        criterioCreatividad.add("Creatividad");

        List<Object> criterioInnovacion = new Vector<Object>();
        criterioInnovacion.add((double) criterio3.getValue());
        criterioInnovacion.add("Innovación");

        Votes.ingresarVotacion(CurrentUser.idUsuario, idProyecto, criterioExpo, criterioCreatividad, criterioInnovacion);
        yaExiste();
    }//GEN-LAST:event_btnVotarActionPerformed

    private void criterio1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_criterio1StateChanged
        lblCriterio1.setText(String.valueOf(criterio1.getValue()));
    }//GEN-LAST:event_criterio1StateChanged

    private void criterio3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_criterio3StateChanged
        lblCriterio3.setText(String.valueOf(criterio3.getValue()));
    }//GEN-LAST:event_criterio3StateChanged

    private void criterio2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_criterio2StateChanged
        lblCriterio2.setText(String.valueOf(criterio2.getValue()));
    }//GEN-LAST:event_criterio2StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Creatividad;
    private javax.swing.JLabel Exposicion;
    public javax.swing.JLabel Img;
    private javax.swing.JLabel Innovacion;
    public javax.swing.JLabel NumCreatividad;
    public javax.swing.JLabel NumExpo;
    public javax.swing.JLabel NumInnovacion;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JButton btnVerMapa;
    private javax.swing.JButton btnVotar;
    private javax.swing.JSlider criterio1;
    private javax.swing.JSlider criterio2;
    private javax.swing.JSlider criterio3;
    private javax.swing.JLabel dot1;
    private javax.swing.JLabel dot2;
    public javax.swing.JLabel id;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane jcpNormal;
    private javax.swing.JLabel jlMapa;
    private javax.swing.JLabel jlPoint;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lblCriterio1;
    private javax.swing.JLabel lblCriterio2;
    private javax.swing.JLabel lblCriterio3;
    private javax.swing.JLabel lblPuntajeFinal;
    private javax.swing.JPanel pnlImg;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlUbicacion;
    public static javax.swing.JPanel pnlView;
    public static javax.swing.JPanel pnlViewImagenes;
    public javax.swing.JPanel pnlViewIntegrantes;
    private javax.swing.JPanel pnlVotacion;
    private javax.swing.JPanel pnlVotos;
    private javax.swing.JLabel stars;
    public static javax.swing.JLabel txtDescView;
    public javax.swing.JLabel txtEspecialidad;
    public javax.swing.JLabel txtNivel;
    public static javax.swing.JLabel txtNombre;
    public javax.swing.JLabel txtNumVotos;
    public javax.swing.JLabel txtPromVoto;
    public javax.swing.JLabel txtSeccion;
    public javax.swing.JLabel txtUbiView;
    // End of variables declaration//GEN-END:variables

}
